repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # You can use a specific revision or version
    hooks:
      - id: flake8

  - repo: local
    rev: ''  # Use the latest version
    hooks:
      - id: pytest
      - name: pytest-check
  
